version: '3.3'

services:
  web:
    build: ./PHP
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: registerDB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./mysql/registerDB.sql:/docker-entrypoint-initdb.d/registerDB.sql
